"""Initial migration

Revision ID: 38717e2b8f7a
Revises: 
Create Date: 2024-09-15 23:41:06.348967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38717e2b8f7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_list',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('permalink', sa.String(length=255), nullable=True),
    sa.Column('media_url', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ig_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('follows_count', sa.Integer(), nullable=False),
    sa.Column('profile_picture_url', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(length=50), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('media_url', sa.String(length=255), nullable=True),
    sa.Column('permalink', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('is_comment_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_shared_to_feed', sa.Boolean(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_details')
    op.drop_table('profile_info')
    op.drop_table('media_list')
    # ### end Alembic commands ###
